@baseUrl=http://localhost:3000/api
@nameSource=products

# Get All
GET {{baseUrl}}/{{nameSource}}
###
# Get All include parent
GET {{baseUrl}}/{{nameSource}}?_expand=category
###
# # Pagination, page default is 1, limit default is 8
GET {{baseUrl}}/{{nameSource}}?_page=1&_limit=8
###
# Get with parent like somethings
GET {{baseUrl}}/{{nameSource}}?categoryId_like=1
###
# Filter ans sort
GET {{baseUrl}}/{{nameSource}}?price_lte=200&_sort=price&_order=asc
###