@baseUrl=http://localhost:3000/api
@nameSource=products

# Get All
GET {{baseUrl}}/{{nameSource}}
###
# Find a product
GET {{baseUrl}}/{{nameSource}}?name_like=pizza
###
# Get product by id
GET {{baseUrl}}/{{nameSource}}/48003
###
# Get All include parent
GET {{baseUrl}}/{{nameSource}}?_expand=category
###
# Get All product by category id
GET {{baseUrl}}/{{nameSource}}?category.id=18458
###
# Get product by category id and id
GET {{baseUrl}}/{{nameSource}}?_expand=category&categoryId_like=18458&id=28677
###
# # Pagination, page default is 1, limit default is 8
GET {{baseUrl}}/{{nameSource}}?_page=1&_limit=8
###
# Get with parent like somethings
GET {{baseUrl}}/{{nameSource}}?categoryId_like=1
###
# Filter ans sort
GET {{baseUrl}}/{{nameSource}}?price_lte=200&_sort=price&_order=asc
###